services:

  mongodb_service:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: lokesh
      MONGO_INITDB_ROOT_PASSWORD: mittal

  mongo_express_service:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lokesh
      ME_CONFIG_MONGODB_ADMINPASSWORD: mittal
      ME_CONFIG_MONGODB_SERVER: mongodb_service
      ME_CONFIG_BASICAUTH:  false

volumes:
  mongo-volume: {}
